package dev.mapselect;

import dev.mapselect.command.GreyCommand;
import dev.mapselect.config.GexpressConfig;
import dev.mapselect.config.RoleModifierTuningConfig;
import dev.mapselect.game.FurnaceDupeGuard;
import dev.mapselect.game.FriendlyFireGuard;
import dev.mapselect.game.GexpressGameModes;
import dev.mapselect.game.LastDeathShieldManager;
import dev.mapselect.game.SpectatorMovementGuard;
import dev.mapselect.item.DevWeaponSkinStamper;
import dev.mapselect.modifier.EodDistribution;
import dev.mapselect.modifier.MutedNotesDistribution;
import dev.mapselect.modifier.NightVisionManager;
import dev.mapselect.modifier.ShortSightedTracker;
import dev.mapselect.network.AbilityCooldownSync;
import dev.mapselect.network.GexpressConfigSyncHandler;
import dev.mapselect.network.GexpressPresetsSyncHandler;
import dev.mapselect.registry.MapSelectBlockEntities;
import dev.mapselect.registry.MapSelectBlocks;
import dev.mapselect.registry.MapSelectItems;
import dev.mapselect.registry.MapSelectModifiers;
import dev.mapselect.registry.MapSelectParticles;
import dev.mapselect.registry.MapSelectRoles;
import dev.mapselect.registry.MapSelectSounds;
import dev.mapselect.role.bombspecialist.C4Detonation;
import dev.mapselect.role.bombspecialist.PliersDefuseManager;
import dev.mapselect.role.medic.MedicShieldManager;
import dev.mapselect.role.KillerRoleInfoManager;
import dev.mapselect.role.GexpressRoleAnnouncementTexts;
import dev.mapselect.role.NeutralWinManager;
import dev.mapselect.role.PassiveMoney;
import dev.mapselect.role.RoleModifierTuningBridge;
import dev.mapselect.role.altruist.AltruistManager;
import dev.mapselect.role.bountyhunter.BountyHunterManager;
import dev.mapselect.role.guardian.GuardianAngelManager;
import dev.mapselect.role.juggernaut.JuggernautManager;
import dev.mapselect.role.mafia.MafiaManager;
import dev.mapselect.role.mafia.TakeoverManager;
import dev.mapselect.role.puppetmaster.PuppetmasterManager;
import dev.mapselect.role.scatterbrain.ScatterBrainManager;
import dev.mapselect.role.seer.SeerManager;
import dev.mapselect.role.silent.SilentShadowManager;
import dev.mapselect.role.skincrawler.SkincrawlerManager;
import dev.mapselect.role.snitch.SnitchManager;
import dev.mapselect.role.spy.SpyManager;
import dev.mapselect.role.timemaster.TimeMasterManager;
import dev.mapselect.role.tracker.TrackerManager;
import dev.mapselect.role.trickster.TricksterManager;
import dev.mapselect.role.vulture.VultureManager;
import dev.mapselect.role.warlock.WarlockManager;
import dev.mapselect.task.FreshAirAreaManager;
import dev.mapselect.voice.DeadVoiceGroupManager;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MapSelect implements ModInitializer {
	public static final String MOD_ID = "gexpress";
	public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

	@Override
	public void onInitialize() {
		GexpressConfig.load();
		RoleModifierTuningConfig.load();
		GexpressRoleAnnouncementTexts.register();
		GexpressGameModes.register();
		MapSelectBlocks.register();
		MapSelectBlockEntities.register();
		MapSelectItems.register();
		MapSelectRoles.register();
		MapSelectModifiers.register();
		RoleModifierTuningBridge.applyConfiguredMaxima();
		MapSelectParticles.register();
		MapSelectSounds.register();
		NeutralWinManager.register();
		FriendlyFireGuard.register();
		LastDeathShieldManager.register();
		SpectatorMovementGuard.register();
		C4Detonation.register();
		PliersDefuseManager.register();
		MedicShieldManager.register();
		SilentShadowManager.register();
		WarlockManager.register();
		JuggernautManager.register();
		TricksterManager.register();
		PuppetmasterManager.register();
		BountyHunterManager.register();
		ScatterBrainManager.register();
		SkincrawlerManager.register();
		SpyManager.register();
		VultureManager.register();
		SnitchManager.register();
		SeerManager.register();
		TimeMasterManager.register();
		TrackerManager.register();
		AltruistManager.register();
		GuardianAngelManager.register();
		TakeoverManager.register();
		MafiaManager.register();
		KillerRoleInfoManager.register();
		FurnaceDupeGuard.register();
		DevWeaponSkinStamper.register();
		EodDistribution.register();
		MutedNotesDistribution.register();
		NightVisionManager.register();
		ShortSightedTracker.register();
		FreshAirAreaManager.register();
		DeadVoiceGroupManager.register();
		AbilityCooldownSync.register();
		PassiveMoney.register();
		GexpressConfigSyncHandler.register();
		GexpressPresetsSyncHandler.register();
		CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) ->
			GreyCommand.register(dispatcher));
		LOGGER.info("Grey's Express initialized - adding /g commands");
	}
}
