package dev.mapselect;

import dev.mapselect.command.GexpressCommand;
import dev.mapselect.bugreport.DiscordBugReportBridge;
import dev.mapselect.block.CoinBarrierManager;
import dev.mapselect.block.FloatingTextManager;
import dev.mapselect.config.GexpressConfig;
import dev.mapselect.config.RoleModifierTuningConfig;
import dev.mapselect.currency.GcoinManager;
import dev.mapselect.game.FurnaceDupeGuard;
import dev.mapselect.game.CouchSleepHandler;
import dev.mapselect.game.FriendlyFireGuard;
import dev.mapselect.game.GexpressGameModes;
import dev.mapselect.game.EndgameRulesManager;
import dev.mapselect.game.LastDeathShieldManager;
import dev.mapselect.game.RoundParticipantTracker;
import dev.mapselect.game.SpectatorMovementGuard;
import dev.mapselect.game.StaticMapResetManager;
import dev.mapselect.game.StaminaCapacityManager;
import dev.mapselect.item.DevWeaponSkinStamper;
import dev.mapselect.level.LevelManager;
import dev.mapselect.modifier.EodDistribution;
import dev.mapselect.modifier.LoversManager;
import dev.mapselect.modifier.MutedNotesDistribution;
import dev.mapselect.modifier.MutedPreferenceManager;
import dev.mapselect.modifier.NightVisionManager;
import dev.mapselect.modifier.ModifierDeathStateManager;
import dev.mapselect.modifier.ShortSightedTracker;
import dev.mapselect.network.ability.AbilityCooldownSync;
import dev.mapselect.network.config.GexpressConfigSyncHandler;
import dev.mapselect.network.preset.GexpressPresetsSyncHandler;
import dev.mapselect.network.progression.ImportedSkinCatalogSync;
import dev.mapselect.preset.map.DefaultMapPresets;
import dev.mapselect.registry.MapSelectBlockEntities;
import dev.mapselect.registry.MapSelectBlocks;
import dev.mapselect.registry.MapSelectEntities;
import dev.mapselect.registry.MapSelectItemGroups;
import dev.mapselect.registry.MapSelectItems;
import dev.mapselect.registry.MapSelectModifiers;
import dev.mapselect.registry.MapSelectParticles;
import dev.mapselect.registry.MapSelectRoles;
import dev.mapselect.registry.MapSelectSounds;
import dev.mapselect.role.bombspecialist.C4Detonation;
import dev.mapselect.role.bombspecialist.PliersDefuseManager;
import dev.mapselect.role.bodyguard.BodyguardManager;
import dev.mapselect.role.medic.MedicShieldManager;
import dev.mapselect.role.KillerRoleInfoManager;
import dev.mapselect.role.GexpressRoleAnnouncementTexts;
import dev.mapselect.role.NeutralWinManager;
import dev.mapselect.role.PassiveMoney;
import dev.mapselect.role.RoundEndRoleRosterSync;
import dev.mapselect.role.RoleModifierTuningBridge;
import dev.mapselect.role.SpecialPairDistributionManager;
import dev.mapselect.role.altruist.AltruistManager;
import dev.mapselect.role.bountyhunter.BountyHunterManager;
import dev.mapselect.role.covenant.CovenantManager;
import dev.mapselect.role.copycat.CopycatManager;
import dev.mapselect.role.cupid.CupidManager;
import dev.mapselect.role.guardian.GuardianAngelManager;
import dev.mapselect.role.juggernaut.JuggernautManager;
import dev.mapselect.role.mafia.MafiaManager;
import dev.mapselect.role.mafia.TakeoverManager;
import dev.mapselect.role.puppetmaster.PuppetmasterManager;
import dev.mapselect.role.painter.PainterManager;
import dev.mapselect.role.scatterbrain.ScatterBrainManager;
import dev.mapselect.role.seer.SeerManager;
import dev.mapselect.role.silent.SilentShadowManager;
import dev.mapselect.role.skincrawler.SkincrawlerManager;
import dev.mapselect.role.sniffer.SnifferManager;
import dev.mapselect.role.snitch.SnitchManager;
import dev.mapselect.role.spy.SpyManager;
import dev.mapselect.role.timemaster.TimeMasterManager;
import dev.mapselect.role.tracker.TrackerManager;
import dev.mapselect.role.twins.TwinsManager;
import dev.mapselect.role.harlequin.HarlequinManager;
import dev.mapselect.role.pelican.PelicanManager;
import dev.mapselect.role.vengeful.VengefulSpiritManager;
import dev.mapselect.role.warlock.WarlockManager;
import dev.mapselect.server.ServerAccessManager;
import dev.mapselect.task.FreshAirAreaManager;
import dev.mapselect.tutorial.TutorialManager;
import dev.mapselect.voice.DeadVoiceGroupManager;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MapSelect implements ModInitializer {
	public static final String MOD_ID = "gexpress";
	public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

	@Override
	public void onInitialize() {
		GexpressConfig.load();
		RoleModifierTuningConfig.load();
		GexpressRoleAnnouncementTexts.register();
		GexpressGameModes.register();
		MapSelectBlocks.register();
		MapSelectBlockEntities.register();
		MapSelectEntities.register();
		MapSelectItems.register();
		MapSelectItemGroups.register();
		MapSelectRoles.register();
		MapSelectModifiers.register();
		RoleModifierTuningBridge.applyConfiguredMaxima();
		MapSelectParticles.register();
		MapSelectSounds.register();
		CoinBarrierManager.register();
		FloatingTextManager.register();
		NeutralWinManager.register();
		FriendlyFireGuard.register();
		EndgameRulesManager.register();
		LastDeathShieldManager.register();
		SpectatorMovementGuard.register();
		StaticMapResetManager.register();
		StaminaCapacityManager.register();
		ServerAccessManager.register();
		CouchSleepHandler.register();
		C4Detonation.register();
		PliersDefuseManager.register();
		BodyguardManager.register();
		MedicShieldManager.register();
		SilentShadowManager.register();
		WarlockManager.register();
		JuggernautManager.register();
		HarlequinManager.register();
		PuppetmasterManager.register();
		BountyHunterManager.register();
		CovenantManager.register();
		CopycatManager.register();
		CupidManager.register();
		VengefulSpiritManager.register();
		ScatterBrainManager.register();
		SkincrawlerManager.register();
		PainterManager.register();
		SpyManager.register();
		PelicanManager.register();
		SnitchManager.register();
		SnifferManager.register();
		SeerManager.register();
		TimeMasterManager.register();
		TrackerManager.register();
		TwinsManager.register();
		AltruistManager.register();
		GuardianAngelManager.register();
		TakeoverManager.register();
		MafiaManager.register();
		KillerRoleInfoManager.register();
		SpecialPairDistributionManager.register();
		RoundParticipantTracker.register();
		RoundEndRoleRosterSync.register();
		FurnaceDupeGuard.register();
		DevWeaponSkinStamper.register();
		EodDistribution.register();
		MutedPreferenceManager.register();
		MutedNotesDistribution.register();
		LoversManager.register();
		ModifierDeathStateManager.register();
		NightVisionManager.register();
		ShortSightedTracker.register();
		FreshAirAreaManager.register();
		TutorialManager.register();
		DeadVoiceGroupManager.register();
		DiscordBugReportBridge.register();
		AbilityCooldownSync.register();
		PassiveMoney.register();
		LevelManager.register();
		GcoinManager.register();
		DefaultMapPresets.register();
		GexpressConfigSyncHandler.register();
		GexpressPresetsSyncHandler.register();
		ImportedSkinCatalogSync.register();
		CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) ->
			GexpressCommand.register(dispatcher));
		LOGGER.info("Grey's Express initialized - adding /g and /gexpress commands");
	}
}
